server.servlet.context-path=/no-sse

spring.application.name=streamable-mcp-no-sse

spring.ai.mcp.server.enabled = true
spring.ai.mcp.server.sseMessageEndpoint = /stream-json
logging.level.org.springframework.ai = DEBUG
logging.level.io.modelcontextprotocol = DEBUG