server.servlet.context-path=/no-sse
server.port=9001

spring.application.name=streamable-mcp-no-sse

spring.ai.mcp.server.enabled = true
spring.ai.mcp.server.sseMessageEndpoint = /stream-json
logging.level.org.springframework.ai = DEBUG
logging.level.io.modelcontextprotocol = DEBUG

eureka.client.service-url.defaultZone=http://localhost:8080/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.instance-id = ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
eureka.instance.prefer-ip-address = true